## Try 3.1.1: Random sampling in Python.




**The dataset below lists the elements present in each painting for a selection of Bob Ross paintings. The code randomly samples from the dataset.**

* **Click the double-right arrow to restart the kernel and run all cells.**
* **Examine the code below.**
* **Note the name of the first painting in the sample, then run the sampling code cell again and notice a different sample was returned.**
* **Modify the code to return a sample of 10 paintings, sampling with replacement.**

In [1]:
# Import pandas package
import pandas as pd

In [2]:
# Load the dataset
# Dataset contains 403 paintings (rows) and 69 features (columns)
paintings = pd.read_csv('bob_ross.csv')

In [3]:
# View dataframe
# Dataframes with more than 60 rows only show the first 5 and last 5 rows
paintings

,EPISODE,TITLE,APPLE_FRAME,AURORA_BOREALIS,BARN,BEACH,BOAT,BRIDGE,BUILDING,BUSHES,...,TOMB_FRAME,TREE,TREES,TRIPLE_FRAME,WATERFALL,WAVES,WINDMILL,WINDOW_FRAME,WINTER,WOOD_FRAMED
0,S01E01,"""A WALK IN THE WOODS""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
1,S01E02,"""MT. MCKINLEY""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,1,0
2,S01E03,"""EBONY SUNSET""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,1,0
3,S01E04,"""WINTER MIST""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
4,S01E05,"""QUIET STREAM""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398,S31E09,"""EVERGREEN VALLEY""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
399,S31E10,"""BALMY BEACH""",0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
400,S31E11,"""LAKE AT THE RIDGE""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
401,S31E12,"""IN THE MIDST OF WINTER""",0,0,1,0,0,0,0,0,...,0,1,1,0,0,0,0,0,1,0
402,S31E13,"""WILDERNESS DAY""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0

In [4]:
# Select a sample of 20 paintings, without replacement, from
# the paintings dataframe
sample20Paintings = paintings.sample(n=20, replace=False)

In [5]:

# View dataframe containing the sampled of paintings
# Dataframes with 60 or fewer rows show all rows
sample20Paintings

,EPISODE,TITLE,APPLE_FRAME,AURORA_BOREALIS,BARN,BEACH,BOAT,BRIDGE,BUILDING,BUSHES,...,TOMB_FRAME,TREE,TREES,TRIPLE_FRAME,WATERFALL,WAVES,WINDMILL,WINDOW_FRAME,WINTER,WOOD_FRAMED
178,S14E10,"""SURPRISING FALLS""",0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0
42,S04E04,"""WINTER SAWSCAPE""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,1,0
72,S06E08,"""HORIZONS WEST""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
11,S01E12,"""SNOWFALL""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
37,S03E12,"""HIDDEN LAKE""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
192,S15E11,"""PATHWAY TO AUTUMN""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
326,S26E02,"""DELIGHTFUL MEADOW HOME""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
295,S23E10,"""FALLS IN THE GLEN""",0,0,0,0,0,0,0,0,...,0,1,1,0,1,0,0,0,0,0
81,S07E04,"""MOUNTAIN CABIN""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
274,S22E02,"""HINT OF SPRINGTIME""",0,0,0,0,0,0,0,1,...,0,1,1,0,1,0,0,0,0,0
176,S14E08,"""ON A CLEAR DAY""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,1,0
291,S23E06,"""RIVER'S PEACE""",0,0,0,0,0,0,0,0,...,0,1,1,0,1,0,0,0,0,0
40,S04E02,"""TRANQUIL VALLEY""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
35,S03E10,"""CAMPFIRE""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
189,S15E08,"""FALL STREAM""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
114,S09E11,"""NATURE'S PARADISE""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
292,S23E07,"""AT DAWN'S LIGHT""",0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,0
22,S02E10,"""LAZY RIVER""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
207,S16E13,"""WOODED STREAM OVAL""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
195,S16E01,"""TWO SEASONS""",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0